version: "3.8"

services:
  app_build:
    build: .
    image: bmbzr_front
    user: node
    env_file: .env
    command: sh -c "yarn && yarn build"
    restart: "no"
    volumes:
      - chapy_front_source:/srv/chapy-front

  pm2:
    image: keymetrics/pm2:latest-alpine
    restart: always
    command: "pm2-runtime start pm2.json"
    user: node
    env_file:
      - .env
    volumes:
      - chapy_front_source:/srv/chapy-front
      - ./pm2.json:/pm2.json
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONT_PORT}:8080"
volumes:
  chapy_front_source:
    name: chapy_front_source
    driver: local
    driver_opts:
      type: non
      device: ${CHAPY_FRONT_PATH}
      o: bind
